version: '2'

services:
  pg:
    image: postgres:14
    volumes:
      - "$PWD/.pg-data/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tanks-monitoring-dev
    ports:
      - "8432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.2
    volumes:
      - "$PWD/.pg-data/pgadmin:/root/.pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=luca@mattivi.io
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8050:80"
    depends_on:
      - pg
